version: '2'
services:

  browsersync:
    image: kevineye/devfile-demo-browsersync
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./docroot:/app/docroot
